import type { Metadata } from "next";

import "./globals.css";
import { Provider } from "./provider";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header/Header";
import { Alegreya_Sans } from "next/font/google";

const alegreyaSans = Alegreya_Sans({
  subsets: ["latin"],
  variable: "--font-alegreya-sans",
  weight: ["100", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${alegreyaSans.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="h-screen flex flex-col">
              <Header />
              <div className="flex-1">{children}</div>
            </div>
          </ThemeProvider>
        </body>
      </Provider>
    </html>
  );
}
